name: sass_builder_example
description: Example to build .css files from .scss source.
environment:
  sdk: '>=2.0.0-dev.51 <2.0.0'
dependencies:
  bootstrap_sass: 4.0.0-alpha.5+1
dev_dependencies:
  build_runner: ^0.8.8
  sass_builder:
    path: ../
