name: sass_builder_example
description: Example to build .css files from .scss source.
environment:
  sdk: '>=2.0.0-dev.51 <3.0.0'
dependencies:
  bootstrap_sass: ^4.1.2
dev_dependencies:
  build_runner: '>=0.8.8 <2.0.0'
  build_web_compilers: ^0.4.0
  sass_builder:
    path: ../
